### ISSUE TITLE
Review JOSS paper

### ISSUE THREAD

**Issue by dirmeier** [JPenuchot/ctbench#27]
Hey, please find my review of your tool below:

- Regarding the manuscript I don't have major comments, other than that there are many typos/grammatical errors, especially in the summary. 

- I found the installation of the package a bit tedious:
    - there is no description how to install on Mac/Windows. The latter can I guess be excused, but if the package is not easily installable/available on Mac this excludes a significant fraction of the research community,
    - to install I needed to use Docker and reproduce what you did [here](https://github.com/JPenuchot/ctbench/tree/main/.github/actions/run-tests-ubuntu) and additionally google how to run `./vcpkg/vcpkg install sciplot fmt` on an ARM. I think it would be easiest to provide a Dockerfile that does the exact installation with all dependencies in the example folder (and have a GitHub action that tests on Mac M1).

- I think providing install instructions using conda would be helpful and also make it straight-forward to use for Mac users. I think all required dependencies are on there.

- I haven't done much C++ development in the last year but seeing how much traction Meson is gaining, I find it unusual that it isn't provided as alternative build system. Would that be easy to offer? Also, is the CMake 3.25 dependency really necessary? 

- I think providing a self-contained example with exact instructions how the [visualisations](https://jpenuchot.github.io/ctbench-docs/md_example_readme.html) are created is helpful. I have probably overlooked something, but it's not 100% clear how you made them from a quick look. 

- Create a CONTRIBUTING file with how-to's on contributing new code.

Cheers, 
Simon

**Comment by JPenuchot** [comment]
Hello Simon, sorry for the delay I didn't catch the notification in my emails.

- MacOS support is not on the roadmap at the moment. Any PR in that regard is more than welcome, but I cannot work on and maintain MacOS support as I have no way to run MacOS outside of GitHub Actions. Conda is not a priority either as other packaging systems like [CPM](https://github.com/cpm-cmake/CPM.cmake) or vcpkg work better with the C++ projects this tool is aimed to work with.

- Meson is not a priority because it has no traction among C++ metaprogramming libraries (eg. [CTRE](https://github.com/hanickadot/compile-time-regular-expressions/), [CTPG](https://github.com/peter-winter/ctpg), [EVE](https://github.com/jfalcou/eve), [Brigand](https://github.com/edouarda/brigand), [Meta](https://github.com/ericniebler/meta), [Boost.mp11](https://github.com/boostorg/mp11)...), which are the kind of libraries this project attempts to evaluate for their compile time performance. However the plot generator executable can be used without the CMake API. I will add a CLI documentation section to explain that, thanks for pointing that out.

- The CMake 3.25 requirement is necessary as already discussed in issue #20 as it is the first CMake version that provides a consistent way to find the compiler launcher executable from the CMake API code.

- ~~The example has no clear instructions indeed~~ erratum: they were in the very first lines of the `CMakeLists.txt` file, I will add them. By the way I added the build steps for the example in the CI, the graph files are expected to be generated in the CMake build folder. Their expected output paths will be added in the example's documentation.

- And you are right, the project is missing contribution guidelines :)

Thank you for your time, I will come back to you as soon as possible.

Regards,
Jules

**Comment by JPenuchot** [comment]
Quick update: I'm working on a vcpkg package. This might not be as quick as I hope but eventually it might make the install process easier, especially and at least hopefully on MacOS.

**Comment by JPenuchot** [comment]
Here's the PR for the ctbench package as a follow-up. The LLVM dependency unsurprisingly makes it very long to iterate on as it needs to be built by vcpkg... I was hoping vcpkg would allow defining optional dependencies to let users pull them as binaries from other sources, but apparently it does not, unless I missed something.

https://github.com/microsoft/vcpkg/pull/31716

PS: Cross-referencing the JOSS issue too for visibility/navigability: https://github.com/openjournals/joss-reviews/issues/5165

**Comment by dirmeier** [comment]
Great, let me know when you are done with the revision. I think only the CONTRIBUTING doc is a requirement. The rest is up to you I guess, but would certainly be nice to have.

**Comment by diehlpk** [comment]
@JPenuchot what is the status about that ticket?
